# Generated by Django 2.1.8 on 2019-09-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_auto_20190919_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_status',
            field=models.IntegerField(default=0),
        ),
    ]
