# Generated by Django 2.1.8 on 2019-09-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='picture',
            field=models.ImageField(default='images/1.jpg', upload_to='iamges'),
            preserve_default=False,
        ),
    ]
